# The application that is statically linked into the kernel image.
#
# This file is included by the top-level Makefile, which compiles these sources
# with the kernel's own flags and links the resulting objects into the kernel.
# It is not meant to be run on its own. To build the kernel with this app:
#
#     make
#
# (See test/Makefile for the alternative test application, built with
#  `make app=tests`.)

app-objects = app/app.o
